language: node_js
deploy:
  provider: firebase
  token:
    secure: "PoorvLEp3f6faNBI9FUN9tHTyv1ond6gDBP8R6Rky9ZbpYadLjw2dLI4HnIDYr08+01TezXtCj979/fnEU+DNMNV1nJKNC44zp56JYAnQwFpL4mZJI3f9M8nJ4rqEZ08I71anu+6E7c0yhVoVWvBhT6zVx7cc2o5BbbyW1aviolo2Bkc5GPqFPUcAvxTtlM/UqhY92D94PjLDnpOD6Q7nQGDPTKMnEFum/3I4/+4J+GmHlbJ7zniqhSbfrG6dvptqlsB/ax5Oy1RCYYrYl1RNsZGH0zAxx6c7iDIxwAg9FMDYPE6HGLEAVnW5o+QK6xrK9CN5QWmlJq+EXgdceC2VDAtshPxYGEPIyczETZ5VyEgCjUegdHU2VtECIMFlGfGVq93jxmxleA7mam9T1THYuArJHbzY9msfNHtmAPVBaJRkVHIoUc/zoZNBZIUG2Xeq6O5vC50W3Z8qhfzL7KXtTViaAA88FrF5LJecbfCsAeYETHmZrn1H8oSOXAtw/oFwXO7satX2TVRgcmRBLbGaGevYyDxc23xOMMN2hhW1D7aXmRe7bvXnXcGT2ycNoqY+eNW4kNypcBKG8pet+dVSedfSIAtjSJ5mp7deTQaUBKFENDUjVH4ihxhvdRU0/lEskmH66TjkdaInlBSBhaAMT3nknBdFBiEBNhlukZEqu0="
  project: "angularhero-3b066"
