language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
    - client/node_modules
    - functions/node_modules
before_install:
- npm i -g firebase-tools
deploy:
  provider: firebase
  skip_cleanup: true
env:
  global:
    secure: uYJNtOVTIRX0IuqiYKN9LZRkgozi8XuqV5ee2x0aWhRca9e9GpCuizFMMgwa+HiP61FWyesZxhIlBXLTeAM1LEydSfRqv/WRNBia9QmvguToUXCLAOYd5eVwCqtAWEIwHm67uvCvV22Cjezrxhpi1EUoLUvhYJW1LTSK+nPMBaA0LOKvdz5rqtcgEgVXS5x97G6LI1BEl3BQKlKOfo5WX8cprp9Qg+tqxIgblgu6mvCn7cRlt10Pd/qN4IuSByRF1SQVxAcuwNv7UWipX0nLoYrttwTrFQQoGU5Q4bm5u6caLfPSR7fPcEbqvQVh8IFjSFTBjdhtIhAvvKbdVb+VZeApG4+dqYdCM+ahtvMxQ6NCvPmEM+Ppna/9bn4roFEz/1NqDWH1mOfxG+8yVI6cfL6XIAd0QoL4Gvw0cE3FHNPi7FR4iWsXzDYR1FRNOHcH75wn5EUnFQGGWAL1YWGO9s9UhoUUPjrQ8Iv/dNAasbTZJn7LwHuyQwG/ANDb60iL5SccxtLk2R+zRRAUaADtSo4+gG9bbQYK43R0RCpX12RfFY6+fd2PLvUBYHvpJsrUpwGhu/SPEOLuBZSawfJ+pS8H9xVOojK6IoBTXZoQLVVP/TRMaWlFwnBXRscMF6pAsUIV+tHCZf9qIHC34sqY/uR7AwKUCb442AkX9qefRq0=
