version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    executor:
      name: node/default
      tag: '10.15'
    steps:
      - checkout
      - restore_cache:
          key: root-cache

      - run: npm install
      - run: cd client && npm install
      - run: cd functions && npm install
      
      - save_cache:
          key: root-cache
          paths:
            - node_modules
            - client/node_modules
            - functions/node_modules
      - run: npm run deploy
# workflows:
#   version: 2
#   main:
#     jobs:
#     - build:
#         filters:
#           branches:
#             only: 
#               - master
