version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    docker:
      - image: cimg/node:16.4.0
    steps:
      - checkout
      - restore_cache:
          keys: 
            - root-cache-{{ checksum "package.json" }}-{{ checksum "client/package.json" }}-{{ checksum "functions/package.json" }}
            - root-cache

      - run: npm install
    
      - save_cache:
          key: root-cache-{{ checksum "package.json" }}-{{ checksum "client/package.json" }}-{{ checksum "functions/package.json" }}
          paths:
            - node_modules
            - client/node_modules
            - functions/node_modules
      - run: npm run build
      - run: npm run deploy
workflows:
  version: 2
  main:
    jobs:
    - build
