version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build-browser:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - root-cache-{{ checksum "package.json" }}-{{ checksum "news/package.json" }}-{{ checksum "functions/package.json" }}
      - run: npm install
      - run: npm ci

      - save_cache:
          key: root-cache-{{ checksum "package.json" }}-{{ checksum "news/package.json" }}-{{ checksum "functions/package.json" }}
          paths:
            - node_modules
            - news/node_modules
            - functions/node_modules
      - run: npm run build:client
      - run: npm run deploy:hosting
  build-server:
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - root-cache-{{ checksum "package.json" }}-{{ checksum "news/package.json" }}-{{ checksum "functions/package.json" }}

      - run: npm install
      - run: npm ci

      - save_cache:
          key: root-cache-{{ checksum "package.json" }}-{{ checksum "news/package.json" }}-{{ checksum "functions/package.json" }}
          paths:
            - node_modules
            - news/node_modules
            - functions/node_modules
      - run: npm run build:server
      - run: npm run deploy:functions

workflows:
  version: 2
  main:
    jobs:
      - build-browser:
         filters:
          branches:
            only: 
              - master
              - function/update-new-firebase
      - build-server:
         filters:
          branches:
            only: 
              - master
              - function/update-new-firebase
