version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-browser:
    docker:
      - image: cimg/node:16.4.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - root-cache-{{ checksum "package.json" }}-{{ checksum "news/package.json" }}-{{ checksum "functions/package.json" }}
            - root-cache

      - run: npm ci

      - save_cache:
          key: root-cache-{{ checksum "package.json" }}-{{ checksum "news/package.json" }}-{{ checksum "functions/package.json" }}
          paths:
            - node_modules
            - news/node_modules
            - functions/node_modules
      - run: npm run build:client
      - run: npm run deploy:hosting
  build-server:
    docker:
      - image: cimg/node:16.4.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - root-cache-{{ checksum "package.json" }}-{{ checksum "news/package.json" }}-{{ checksum "functions/package.json" }}
            - root-cache

      - run: npm ci

      - save_cache:
          key: root-cache-{{ checksum "package.json" }}-{{ checksum "news/package.json" }}-{{ checksum "functions/package.json" }}
          paths:
            - node_modules
            - news/node_modules
            - functions/node_modules
      - run: npm run build:server
      - run: npm run deploy:functions

workflows:
  version: 2
  main:
    jobs:
      - build-browser:
        #  filters:
        #   branches:
        #     only: 
        #       - master
        #       - test-get-back-tinhte

      - build-server:
        #  filters:
        #   branches:
        #     only: 
        #       - master
        #       - test-get-back-tinhte
